FROM node:16-alpine

WORKDIR /app

# Install dependencies
COPY server/package.json server/package-lock.json ./
RUN npm ci --production

# Copy app files
COPY server/ ./

# Create necessary directories
RUN mkdir -p /app/streams/hls /app/streams/temp

# Install FFmpeg
RUN apk add --no-cache ffmpeg

EXPOSE 3000
CMD ["node", "src/server.js"]